namespace PostXING.Controls;

public enum EnableScrollBarFlags
{
	ESB_ENABLE_BOTH = 0,
	ESB_DISABLE_BOTH = 3,
	ESB_DISABLE_LEFT = 1,
	ESB_DISABLE_RIGHT = 2,
	ESB_DISABLE_UP = 1,
	ESB_DISABLE_DOWN = 2,
	ESB_DISABLE_LTUP = 1,
	ESB_DISABLE_RTDN = 2
}
