namespace PostXING.Controls;

public enum SetErrorModeFlags
{
	SEM_DEFAULT = 0,
	SEM_FAILCRITICALERRORS = 1,
	SEM_NOGPFAULTERRORBOX = 2,
	SEM_NOALIGNMENTFAULTEXCEPT = 4,
	SEM_NOOPENFILEERRORBOX = 0x8000
}
