using System.Globalization;
using PostXING.Core.Domain;

namespace PostXING.GitHub;

public sealed class GitHubPublishService(IGitHubGateway gateway, TimeProvider? clock = null)
{
    private readonly TimeProvider _clock = clock ?? TimeProvider.System;

    public async Task<PublishState> PublishAsync(
        Post post,
        SiteConfig site,
        string renderedDocument,
        bool autoMerge,
        CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(post);
        ArgumentNullException.ThrowIfNull(site);
        ArgumentNullException.ThrowIfNull(renderedDocument);

        var state = PublishState.Initial;

        var baseSha = await gateway.GetBranchShaAsync(site.Owner, site.Repo, site.DevelopBranch, ct);
        var publishDate = DateOnly.FromDateTime(_clock.GetUtcNow().UtcDateTime);
        var branchName = $"post/{post.Slug.Value}-{publishDate.ToString("yyyyMMdd", CultureInfo.InvariantCulture)}";
        await gateway.CreateBranchAsync(site.Owner, site.Repo, branchName, baseSha, ct);
        state = state.WithBranch(branchName);

        var postPath = $"posts/{publishDate:yyyy-MM-dd}-{post.Slug.Value}.md";
        var commitMessage = $"post: {post.FrontMatter.Title} ({post.Slug.Value})";
        await gateway.UpsertFileAsync(site.Owner, site.Repo, branchName, postPath, renderedDocument, commitMessage, null, ct);

        var prNumber = await gateway.OpenPullRequestAsync(
            site.Owner, site.Repo, branchName, site.DevelopBranch,
            title: $"Post: {post.FrontMatter.Title}",
            body: BuildPrBody(post, publishDate),
            ct);
        state = state.WithPullRequest(prNumber);

        if (!autoMerge) return state;

        var status = await WaitForChecksAsync(site, prNumber, ct);
        if (!ChecksPassed(status))
        {
            var summary = string.Join(", ", status.Checks.Select(c => $"{c.Name}={c.Conclusion ?? c.Status}"));
            return state.WithFailure($"Checks did not pass: {summary}");
        }

        var sha = await gateway.MergePullRequestAsync(site.Owner, site.Repo, prNumber, MergeStrategy.Squash, ct);
        return state.WithMerged(sha);
    }

    public Task<PublishState> SaveDraftAsync(
        Post post,
        SiteConfig site,
        string renderedDocument,
        CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(post);
        ArgumentNullException.ThrowIfNull(site);
        ArgumentNullException.ThrowIfNull(renderedDocument);

        var path = $"drafts/{post.Slug.Value}.md";
        var message = $"draft: {post.FrontMatter.Title} ({post.Slug.Value})";
        return UpsertDirectAsync(site, path, renderedDocument, message, ct);
    }

    private async Task<PublishState> UpsertDirectAsync(SiteConfig site, string path, string content, string message, CancellationToken ct)
    {
        var existing = await gateway.GetFileContentAsync(site.Owner, site.Repo, site.DevelopBranch, path, ct);
        await gateway.UpsertFileAsync(site.Owner, site.Repo, site.DevelopBranch, path, content, message,
            existingFileSha: existing is null ? null : await GetFileShaAsync(site, path, ct), ct);
        return PublishState.Initial;
    }

#pragma warning disable CA1822
    private async Task<string?> GetFileShaAsync(SiteConfig site, string path, CancellationToken ct)
    {
        await Task.CompletedTask;
        return null;
    }
#pragma warning restore CA1822

    private static string BuildPrBody(Post post, DateOnly publishDate) =>
        $"Auto-generated by PostXING 4.0\n\nslug: `{post.Slug.Value}`\npublish date: {publishDate:O}\ndraft: {post.FrontMatter.Draft}";

    private async Task<PullRequestStatus> WaitForChecksAsync(SiteConfig site, int prNumber, CancellationToken ct)
    {
        var deadline = _clock.GetUtcNow().AddMinutes(10);
        while (_clock.GetUtcNow() < deadline)
        {
            var status = await gateway.GetPullRequestStatusAsync(site.Owner, site.Repo, prNumber, ct);
            if (status.Mergeable == true && status.Checks.Count > 0 && status.Checks.All(c => c.Status == "completed"))
                return status;
            await Task.Delay(TimeSpan.FromSeconds(5), _clock, ct);
        }
        return await gateway.GetPullRequestStatusAsync(site.Owner, site.Repo, prNumber, ct);
    }

    private static bool ChecksPassed(PullRequestStatus s) =>
        s.Mergeable == true
        && s.Checks.Count > 0
        && s.Checks.All(c => string.Equals(c.Conclusion, "success", StringComparison.OrdinalIgnoreCase));
}
