using System.Globalization;
using PostXING.Core.Domain;

namespace PostXING.GitHub;

public sealed class GitHubPublishService(IGitHubGateway gateway, TimeProvider? clock = null)
{
    private readonly TimeProvider _clock = clock ?? TimeProvider.System;

    public async Task<PublishState> PublishAsync(
        Post post,
        SiteConfig site,
        string renderedDocument,
        bool autoMerge,
        string? existingPostPath = null,
        CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(post);
        ArgumentNullException.ThrowIfNull(site);
        ArgumentNullException.ThrowIfNull(renderedDocument);

        var state = PublishState.Initial;

        var baseSha = await gateway.GetBranchShaAsync(site.Owner, site.Repo, site.DevelopBranch, ct);
        var now = _clock.GetUtcNow().UtcDateTime;
        var publishDate = DateOnly.FromDateTime(now);
        // Second precision so two re-publishes of the same post on the same day don't collide on
        // an identical ephemeral branch name (gh #48). The branch is throwaway; only the post path is stable.
        var branchName = $"post/{post.Slug.Value}-{now.ToString("yyyyMMddHHmmss", CultureInfo.InvariantCulture)}";
        await gateway.CreateBranchAsync(site.Owner, site.Repo, branchName, baseSha, ct);
        state = state.WithBranch(branchName);

        // Re-publishing an already-published post writes back to its original path (permalink stability);
        // a first publish (existingPostPath null) mints a today-dated path (gh #48).
        var postPath = existingPostPath ?? $"{site.PostsPrefix}{publishDate:yyyy-MM-dd}-{post.Slug.Value}.md";
        var commitMessage = $"post: {post.FrontMatter.Title} ({post.Slug.Value})";
        await gateway.UpsertFileAsync(site.Owner, site.Repo, branchName, postPath, renderedDocument, commitMessage, null, ct);

        var prNumber = await gateway.OpenPullRequestAsync(
            site.Owner, site.Repo, branchName, site.DevelopBranch,
            title: $"Post: {post.FrontMatter.Title}",
            body: BuildPrBody(post, publishDate),
            ct);
        state = state.WithPullRequest(prNumber);

        if (!autoMerge) return state;

        var status = await WaitForChecksAsync(site, prNumber, ct);
        if (!ChecksPassed(status))
        {
            var summary = string.Join(", ", status.Checks.Select(c => $"{c.Name}={c.Conclusion ?? c.Status}"));
            return state.WithFailure($"Checks did not pass: {summary}");
        }

        var sha = await gateway.MergePullRequestAsync(site.Owner, site.Repo, prNumber, MergeStrategy.Squash, ct);
        return state.WithMerged(sha);
    }

    public Task<PublishState> SaveDraftAsync(
        Post post,
        SiteConfig site,
        string renderedDocument,
        CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(post);
        ArgumentNullException.ThrowIfNull(site);
        ArgumentNullException.ThrowIfNull(renderedDocument);

        var path = $"{site.DraftsPrefix}{post.Slug.Value}.md";
        var message = $"draft: {post.FrontMatter.Title} ({post.Slug.Value})";
        return UpsertDirectAsync(site, path, renderedDocument, message, ct);
    }

    /// <summary>Writes <paramref name="content"/> to the existing <paramref name="path"/> on
    /// <see cref="SiteConfig.DevelopBranch"/> (drafts/ or posts/), preserving location. Used by
    /// the editor's Save on a GitHub-backed post — the file's path is what was opened.</summary>
    public Task<PublishState> SaveToBranchAsync(
        SiteConfig site,
        string path,
        string content,
        string commitMessage,
        CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(site);
        ArgumentException.ThrowIfNullOrWhiteSpace(path);
        ArgumentNullException.ThrowIfNull(content);
        return UpsertDirectAsync(site, path, content, commitMessage, ct);
    }

    private async Task<PublishState> UpsertDirectAsync(SiteConfig site, string path, string content, string message, CancellationToken ct)
    {
        // One round-trip for the sha (also serves as the existence probe); the Contents API
        // rejects PUT on an existing path unless a sha is supplied, so we can't skip this.
        var existingSha = await gateway.GetFileShaAsync(site.Owner, site.Repo, site.DevelopBranch, path, ct);
        await gateway.UpsertFileAsync(site.Owner, site.Repo, site.DevelopBranch, path, content, message,
            existingFileSha: existingSha, ct);
        return PublishState.Initial;
    }

    private static string BuildPrBody(Post post, DateOnly publishDate) =>
        $"Auto-generated by PostXING 4.0\n\nslug: `{post.Slug.Value}`\npublish date: {publishDate:O}\ndraft: {post.FrontMatter.Draft}";

    private async Task<PullRequestStatus> WaitForChecksAsync(SiteConfig site, int prNumber, CancellationToken ct)
    {
        var deadline = _clock.GetUtcNow().AddMinutes(10);
        while (_clock.GetUtcNow() < deadline)
        {
            var status = await gateway.GetPullRequestStatusAsync(site.Owner, site.Repo, prNumber, ct);
            if (status.Mergeable == true && status.Checks.Count > 0 && status.Checks.All(c => c.Status == "completed"))
                return status;
            await Task.Delay(TimeSpan.FromSeconds(5), _clock, ct);
        }
        return await gateway.GetPullRequestStatusAsync(site.Owner, site.Repo, prNumber, ct);
    }

    private static bool ChecksPassed(PullRequestStatus s) =>
        s.Mergeable == true
        && s.Checks.Count > 0
        && s.Checks.All(c => string.Equals(c.Conclusion, "success", StringComparison.OrdinalIgnoreCase));
}
