using PostXING.Core.Domain;

namespace PostXING.GitHub;

public sealed class GitHubPublishService(IGitHubGateway gateway, TimeProvider? clock = null)
{
    private readonly TimeProvider _clock = clock ?? TimeProvider.System;

    public async Task<PublishState> PublishAsync(
        Post post,
        SiteConfig site,
        string renderedDocument,
        bool autoMerge,
        CancellationToken ct = default)
    {
        ArgumentNullException.ThrowIfNull(post);
        ArgumentNullException.ThrowIfNull(site);
        ArgumentNullException.ThrowIfNull(renderedDocument);

        var state = PublishState.Initial;

        var baseSha = await gateway.GetBranchShaAsync(site.Owner, site.Repo, site.DevelopBranch, ct);
        var branchName = $"post/{post.Slug.Value}-{post.CreatedAt:yyyyMMdd}";
        await gateway.CreateBranchAsync(site.Owner, site.Repo, branchName, baseSha, ct);
        state = state.WithBranch(branchName);

        var path = post.RelativePath(site.ContentRoot);
        var commitMessage = $"post: {post.FrontMatter.Title} ({post.Slug.Value})";
        await gateway.UpsertFileAsync(site.Owner, site.Repo, branchName, path, renderedDocument, commitMessage, null, ct);

        var prNumber = await gateway.OpenPullRequestAsync(
            site.Owner, site.Repo, branchName, site.DevelopBranch,
            title: $"Post: {post.FrontMatter.Title}",
            body: BuildPrBody(post),
            ct);
        state = state.WithPullRequest(prNumber);

        if (!autoMerge) return state;

        var status = await WaitForChecksAsync(site, prNumber, ct);
        if (!ChecksPassed(status))
        {
            var summary = string.Join(", ", status.Checks.Select(c => $"{c.Name}={c.Conclusion ?? c.Status}"));
            return state.WithFailure($"Checks did not pass: {summary}");
        }

        var sha = await gateway.MergePullRequestAsync(site.Owner, site.Repo, prNumber, MergeStrategy.Squash, ct);
        return state.WithMerged(sha);
    }

    private static string BuildPrBody(Post post) =>
        $"Auto-generated by PostXING 4.0\n\nslug: `{post.Slug.Value}`\ndate: {post.CreatedAt:O}\ndraft: {post.FrontMatter.Draft}";

    private async Task<PullRequestStatus> WaitForChecksAsync(SiteConfig site, int prNumber, CancellationToken ct)
    {
        var deadline = _clock.GetUtcNow().AddMinutes(10);
        while (_clock.GetUtcNow() < deadline)
        {
            var status = await gateway.GetPullRequestStatusAsync(site.Owner, site.Repo, prNumber, ct);
            if (status.Mergeable == true && status.Checks.Count > 0 && status.Checks.All(c => c.Status == "completed"))
                return status;
            try
            {
                await Task.Delay(TimeSpan.FromSeconds(5), _clock, ct);
            }
            catch (OperationCanceledException)
            {
                throw;
            }
        }
        return await gateway.GetPullRequestStatusAsync(site.Owner, site.Repo, prNumber, ct);
    }

    private static bool ChecksPassed(PullRequestStatus s) =>
        s.Mergeable == true
        && s.Checks.Count > 0
        && s.Checks.All(c => string.Equals(c.Conclusion, "success", StringComparison.OrdinalIgnoreCase));
}
